### ISSUE TITLE
Composer Error

### ISSUE THREAD

**Issue by saltpeanuts** [nlemoine/bolt-extension-minify-html#1]
Trying to install the extension with Bolt 3.1.3 and I'm getting a composer error:

`hellonico/minify-html 0.1.1 requires wyrihaximus/html-compress ^1.2 -> no matching package found`

**Comment by jamiroconca** [comment]
hi,

i confirm this issue, this extension fails to install

**Comment by nlemoine** [comment]
Hi, 

Sorry about that. I didn't know until recently that bolt extensions don't allow requiring packages from packagist. 

So I added all packages to the extension, which is a bummer but is for now the only to get this working. However, it should work now.

Please let me know if you encounter any bugs.
