### ISSUE TITLE
Problem when running alongside the Bolt Better Thumbs extension. 

### ISSUE THREAD

**Issue by saltpeanuts** [nlemoine/bolt-extension-minify-html#9]
Prevents the loading of generated srcset images. More details over here:

https://github.com/cdowdy/boltbetterthumbs/issues/18

**Comment by nlemoine** [comment]
Can you install the extension on the develop branch and tell me if it's ok for you?

**Comment by saltpeanuts** [comment]
Just gave it a try with dev-develop, but still having the same problem unfortunately.

**Comment by nlemoine** [comment]
Are you sure you installed the develop branch? Anywhere I can check out the issue?
You have to set extensions/stability to `dev` in your app/config file to enable dev branch installation.

**Comment by saltpeanuts** [comment]
Testing locally at the moment. 

`minimum-stability: dev` gives me two options: dev-develop and dev-master. I installed dev-develop, is that the correct one?

**Comment by nlemoine** [comment]
Yep

**Comment by saltpeanuts** [comment]
Ok I've just removed completely and re-installed, instead of choosing 'install different version' and dev-develop seems to be working now.

**Comment by nlemoine** [comment]
Thanks for your feedback. I'll release a new version with the fix.
